const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const ROOT=__dirname,DATA=path.join(ROOT,'src/_data/hfk.json'),BLOG=path.join(ROOT,'src/blog'),PORT=Number(process.env.HFK_ADMIN_PORT||8787);
const read=()=>JSON.parse(fs.readFileSync(DATA,'utf8'));const write=d=>fs.writeFileSync(DATA,JSON.stringify(d,null,2)+'\n');
const slug=s=>String(s||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
const json=(r,c,d)=>{r.writeHead(c,{'Content-Type':'application/json','Cache-Control':'no-store'});r.end(JSON.stringify(d))};
const body=q=>new Promise((ok,no)=>{let b='';q.on('data',x=>{b+=x;if(b.length>3e6)q.destroy()});q.on('end',()=>{try{ok(JSON.parse(b||'{}'))}catch(e){no(e)}})});
const postFiles=()=>fs.existsSync(BLOG)?fs.readdirSync(BLOG).filter(x=>x.endsWith('.md')):[];
const readPost=file=>{const raw=fs.readFileSync(path.join(BLOG,file),'utf8'),m=raw.match(/^---\s*([\s\S]*?)\s*---/),fm={};(m?m[1]:'').split(/\r?\n/).forEach(l=>{const x=l.match(/^([\w-]+):\s*(.*)$/);if(x)fm[x[1]]=x[2].replace(/^['"]|['"]$/g,'')});return{file,title:fm.title||file.replace('.md',''),date:fm.date||'',category:(fm.tags||'').replace(/[\[\]"]/g,'').split(',')[0].trim(),description:fm.description||'',content:m?raw.slice(m[0].length).trim():raw}};
const state=()=>{const d=read();return{...d,posts:postFiles().map(readPost)}};
const normalizeIg=u=>String(u||'').trim().replace(/\/$/,'').replace(/^http:\/\//i,'https://').replace(/^https:\/\/instagram\.com/i,'https://www.instagram.com');
const validIg=u=>/^https:\/\/(www\.)?instagram\.com\/(p|reel|tv)\//i.test(normalizeIg(u));
const normalizeUrl=u=>String(u||'').trim();
const clean=s=>String(s||'').replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/\r?\n/g,' ');
const savePost=(x,file)=>fs.writeFileSync(path.join(BLOG,file),['---','layout: layouts/post.njk','title: "'+clean(x.title)+'"','date: '+(x.date||new Date().toISOString().slice(0,10)),'tags: ["'+clean(x.category||'Sneakers')+'"]','description: "'+clean(x.seoDescription||x.description||x.excerpt||'')+'"','---','',x.content||'',''].join('\n'));
async function handler(q,r){const u=new URL(q.url,'http://127.0.0.1'),p=u.pathname;
if(q.method==='GET'&&p==='/api/state')return json(r,200,state());
if(q.method==='POST'&&p==='/api/celebrities'){const x=await body(q),d=read(),s=slug(x.name);if(!s||d.celebrities.some(v=>v.slug===s))return json(r,400,{error:'Celebrity already exists'});d.celebrities.push({name:x.name,slug:s,instagram:x.instagram||'',bio:x.bio||'',updateCount:0});write(d);return json(r,201,{ok:true})}
if(q.method==='PUT'&&p.startsWith('/api/celebrities/')){const old=decodeURIComponent(p.split('/')[3]),x=await body(q),d=read(),v=d.celebrities.find(v=>v.slug===old);if(!v)return json(r,404,{error:'Celebrity not found'});const s=slug(x.name||v.name);if(d.celebrities.some(z=>z!==v&&z.slug===s))return json(r,400,{error:'Celebrity slug already exists'});v.name=x.name||v.name;v.instagram=x.instagram??v.instagram;v.bio=x.bio??v.bio;v.slug=s;d.updates.forEach(z=>{if(z.celebritySlug===old){z.celebritySlug=s;z.celebrityName=v.name}});write(d);return json(r,200,{ok:true})}
if(q.method==='DELETE'&&p.startsWith('/api/celebrities/')){const s=decodeURIComponent(p.split('/')[3]),d=read(),i=d.celebrities.findIndex(v=>v.slug===s);if(i<0)return json(r,404,{error:'Celebrity not found'});d.celebrities.splice(i,1);d.updates=d.updates.filter(v=>v.celebritySlug!==s);write(d);return json(r,200,{ok:true})}
if(q.method==='POST'&&p==='/api/shoes'){const x=await body(q),d=read(),s=slug((x.brand||'')+' '+(x.name||''));if(!x.brand||!x.name||d.shoes.some(v=>v.slug===s))return json(r,400,{error:'Shoe already exists or fields missing'});d.shoes.push({brand:x.brand,name:x.name,slug:s,description:x.description||'',affiliates:[]});write(d);return json(r,201,{ok:true})}
if(q.method==='PUT'&&p.startsWith('/api/shoes/')&&!p.endsWith('/affiliates')){const old=decodeURIComponent(p.split('/')[3]),x=await body(q),d=read(),v=d.shoes.find(v=>v.slug===old);if(!v)return json(r,404,{error:'Shoe not found'});const s=slug((x.brand||v.brand)+' '+(x.name||v.name));v.brand=x.brand||v.brand;v.name=x.name||v.name;v.description=x.description??v.description;v.slug=s;d.updates.forEach(z=>{if(z.shoeSlug===old){z.shoeSlug=s;z.shoeName=v.brand+' '+v.name}});write(d);return json(r,200,{ok:true})}
if(q.method==='DELETE'&&p.startsWith('/api/shoes/')){const s=decodeURIComponent(p.split('/')[3]),d=read(),i=d.shoes.findIndex(v=>v.slug===s);if(i<0)return json(r,404,{error:'Shoe not found'});d.shoes.splice(i,1);d.updates=d.updates.filter(v=>v.shoeSlug!==s);write(d);return json(r,200,{ok:true})}
if(q.method==='PUT'&&p.startsWith('/api/shoes/')&&p.endsWith('/affiliates')){const s=decodeURIComponent(p.split('/')[3]),x=await body(q),d=read(),v=d.shoes.find(v=>v.slug===s);if(!v)return json(r,404,{error:'Shoe not found'});v.affiliates=Array.isArray(x.affiliates)?x.affiliates:[];write(d);return json(r,200,{ok:true})}
if(q.method==='POST'&&p==='/api/updates'){const x=await body(q),d=read(),c=d.celebrities.find(v=>v.slug===x.celebritySlug),s=d.shoes.find(v=>v.slug===x.shoeSlug);if(!c)return json(r,400,{error:'Celebrity not found'});if(x.shoeSlug&&!s)return json(r,400,{error:'Shoe not found'});if(!validIg(x.instagramUrl))return json(r,400,{error:'Invalid Instagram URL'});const ig=normalizeIg(x.instagramUrl);if(d.updates.some(v=>normalizeIg(v.instagramUrl)===ig))return json(r,409,{error:'This Instagram post is already added'});d.updates.unshift({id:crypto.randomUUID(),celebritySlug:c.slug,celebrityName:c.name,shoeSlug:s?s.slug:'',shoeName:s?s.brand+' '+s.name:'',instagramUrl:ig,date:x.date||new Date().toISOString().slice(0,10),occasion:x.occasion||'',description:x.description||''});c.updateCount=(c.updateCount||0)+1;write(d);return json(r,201,{ok:true})}
if(q.method==='PUT'&&p.startsWith('/api/updates/')){const id=decodeURIComponent(p.split('/')[3]),x=await body(q),d=read(),v=d.updates.find(v=>v.id===id);if(!v)return json(r,404,{error:'Update not found'});const c=d.celebrities.find(v=>v.slug===x.celebritySlug),s=d.shoes.find(v=>v.slug===x.shoeSlug);if(!c)return json(r,400,{error:'Celebrity not found'});if(x.shoeSlug&&!s)return json(r,400,{error:'Shoe not found'});if(x.instagramUrl&&!validIg(x.instagramUrl))return json(r,400,{error:'Invalid Instagram URL'});if(x.instagramUrl){const ig=normalizeIg(x.instagramUrl);if(d.updates.some(z=>z!==v&&normalizeIg(z.instagramUrl)===ig))return json(r,409,{error:'This Instagram post is already used'});v.instagramUrl=ig;}Object.assign(v,{celebritySlug:c.slug,celebrityName:c.name,shoeSlug:s?s.slug:'',shoeName:s?s.brand+' '+s.name:'',instagramUrl:x.instagramUrl||v.instagramUrl,date:x.date||v.date,occasion:x.occasion??v.occasion,description:x.description??v.description});write(d);return json(r,200,{ok:true})}
if(q.method==='DELETE'&&p.startsWith('/api/updates/')){const id=decodeURIComponent(p.split('/')[3]),d=read(),i=d.updates.findIndex(v=>v.id===id);if(i<0)return json(r,404,{error:'Update not found'});d.updates.splice(i,1);write(d);return json(r,200,{ok:true})}
if(q.method==='POST'&&p==='/api/posts'){const x=await body(q),s=slug(x.slug||x.title),file=s+'.md';if(!s)return json(r,400,{error:'Title required'});if(fs.existsSync(path.join(BLOG,file)))return json(r,409,{error:'Post already exists'});savePost(x,file);return json(r,201,{ok:true,file})}
if(q.method==='PUT'&&p.startsWith('/api/posts/')){const old=decodeURIComponent(p.split('/')[3]),x=await body(q),oldPath=path.join(BLOG,old);if(!fs.existsSync(oldPath))return json(r,404,{error:'Post not found'});const file=slug(x.slug||x.title||old.replace('.md',''))+'.md';if(file!==old&&fs.existsSync(path.join(BLOG,file)))return json(r,409,{error:'Post slug already exists'});if(file!==old)fs.renameSync(oldPath,path.join(BLOG,file));savePost(x,file);return json(r,200,{ok:true,file})}
if(q.method==='DELETE'&&p.startsWith('/api/posts/')){const file=decodeURIComponent(p.split('/')[3]),f=path.join(BLOG,file);if(!fs.existsSync(f))return json(r,404,{error:'Post not found'});fs.unlinkSync(f);return json(r,200,{ok:true})}
if(q.method==='GET'){const f=p==='/'?path.join(ROOT,'admin/index.html'):path.join(ROOT,p.slice(1));if(f.startsWith(ROOT)&&fs.existsSync(f)&&fs.statSync(f).isFile()){const ext=path.extname(f);r.writeHead(200,{'Content-Type':ext==='.css'?'text/css':ext==='.js'?'application/javascript':'text/html; charset=utf-8'});return fs.createReadStream(f).pipe(r)}}return json(r,404,{error:'Not found'})}
http.createServer((q,r)=>handler(q,r).catch(e=>json(r,500,{error:e.message}))).listen(PORT,'127.0.0.1',()=>console.log('HFK Studio → http://127.0.0.1:'+PORT));
