const app=document.getElementById("app");const navs=[...document.querySelectorAll(".nav")];let state={};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
async function api(url,opt){const r=await fetch(url,{headers:{"Content-Type":"application/json"},...opt});const data=await r.json();if(!r.ok)throw Error(data.error||"Request failed");return data}
async function load(){state=await api("/admin/api/state");render("dashboard")}
function shell(title,body){app.innerHTML='<div class="page-head"><h1>'+title+'</h1></div>'+body}
function render(view){navs.forEach(n=>n.classList.toggle("active",n.dataset.view===view));if(view==="dashboard")return dashboard();if(view==="updates")return updateForm();if(view==="posts")return posts();if(view==="celebrities")return celebrities();if(view==="shoes")return shoes();if(view==="affiliates")return affiliates()}
function dashboard(){shell("Dashboard",'<div class="grid"><div class="stat"><strong>'+state.posts.length+'</strong><span>Blog posts</span></div><div class="stat"><strong>'+state.celebrities.length+'</strong><span>Celebrities</span></div><div class="stat"><strong>'+state.shoes.length+'</strong><span>Shoes</span></div><div class="stat"><strong>'+state.updates.length+'</strong><span>Fashion updates</span></div></div><div class="panel" style="margin-top:18px"><h2>Quick workflow</h2><p>Find a public Instagram post, choose the celebrity and shoe, then publish the update. HFK Studio writes the data used by Eleventy.</p><button class="btn" onclick="render(\'updates\')">+ Quick Update</button></div>')}
function updateForm(){shell("Quick Update",'<div class="panel"><form id="updateForm" class="form"><div class="two"><label>Celebrity<select id="uCelebrity">'+state.celebrities.map(c=>'<option value="'+esc(c.slug)+'">'+esc(c.name)+'</option>').join("")+'</select></label><label>Shoe<select id="uShoe"><option value="">No shoe / unknown</option>'+state.shoes.map(s=>'<option value="'+esc(s.slug)+'">'+esc(s.brand+" "+s.name)+'</option>').join("")+'</select></label></div><label>Instagram post URL<input id="uInstagram" type="url" placeholder="https://www.instagram.com/p/..." required></label><div class="two"><label>Date<input id="uDate" type="date" value="'+new Date().toISOString().slice(0,10)+'"></label><label>Occasion<input id="uOccasion" placeholder="Airport, event, casual..."></label></div><label>Description<textarea id="uDescription" placeholder="What is notable about this look?"></textarea></label><div id="uNotice"></div><div class="actions"><button class="btn" type="submit">Save Update</button></div></form></div>');document.getElementById("updateForm").onsubmit=async e=>{e.preventDefault();try{await api("/admin/api/updates",{method:"POST",body:JSON.stringify({celebritySlug:uCelebrity.value,shoeSlug:uShoe.value,instagramUrl:uInstagram.value,date:uDate.value,occasion:uOccasion.value,description:uDescription.value})});await load();render("updates");document.getElementById("uNotice").innerHTML='<div class="notice success">Saved. Run your Eleventy build to preview the new page.</div>'}catch(err){document.getElementById("uNotice").innerHTML='<div class="notice error">'+esc(err.message)+'</div>'}}}
function celebrities(){shell("Celebrities",'<div class="panel"><form id="cForm" class="form"><div class="two"><label>Name<input id="cName" required></label><label>Instagram username<input id="cInstagram" placeholder="@username"></label></div><label>Bio<textarea id="cBio" style="min-height:100px"></textarea></label><button class="btn">Add Celebrity</button></form></div><div class="list">'+state.celebrities.map(c=>'<div class="row"><div><h3>'+esc(c.name)+'</h3><small>/celebrities/'+esc(c.slug)+'/</small></div></div>').join("")+'</div>');document.getElementById("cForm").onsubmit=async e=>{e.preventDefault();await api("/admin/api/celebrities",{method:"POST",body:JSON.stringify({name:cName.value,instagram:cInstagram.value,bio:cBio.value})});await load();render("celebrities")}}
function shoes(){shell("Shoes",'<div class="panel"><form id="sForm" class="form"><div class="two"><label>Brand<input id="sBrand" required></label><label>Model<input id="sName" required></label></div><label>Description<textarea id="sDescription" style="min-height:100px"></textarea></label><button class="btn">Add Shoe</button></form></div><div class="list">'+state.shoes.map(s=>'<div class="row"><div><h3>'+esc(s.brand+" "+s.name)+'</h3><small>/shoes/'+esc(s.slug)+'/ · '+(s.affiliates||[]).length+' offers</small></div></div>').join("")+'</div>');document.getElementById("sForm").onsubmit=async e=>{e.preventDefault();await api("/admin/api/shoes",{method:"POST",body:JSON.stringify({brand:sBrand.value,name:sName.value,description:sDescription.value})});await load();render("shoes")}}
function affiliates(){shell("Affiliate Links",'<div class="panel"><p>Select a shoe below to manage its retailer links.</p>'+state.shoes.map(s=>'<div class="row"><div><h3>'+esc(s.brand+" "+s.name)+'</h3><small>'+((s.affiliates||[]).length)+' affiliate offers</small></div><button class="btn secondary" onclick="editAff(\''+esc(s.slug)+'\')">Manage</button></div>').join("")+'</div>')}
function editAff(slug){const s=state.shoes.find(x=>x.slug===slug);shell("Affiliate Links — "+esc(s.brand+" "+s.name),'<div class="panel"><div id="affRows">'+(s.affiliates||[]).map((a,i)=>affRow(a,i)).join("")+'</div><button class="btn secondary" onclick="addAffRow()">+ Add retailer</button><div class="actions" style="margin-top:16px"><button class="btn" onclick="saveAff(\''+esc(slug)+'\')">Save links</button></div></div>')}
function affRow(a={},i=0){return '<div class="affiliate-row" data-i="'+i+'"><label>Retailer<input class="ar-retailer" value="'+esc(a.retailer||"")+'"></label><label>URL<input class="ar-url" type="url" value="'+esc(a.url||"")+'"></label><label>Label<input class="ar-label" value="'+esc(a.label||"Check price")+'"></label><button type="button" class="btn danger" onclick="this.parentElement.remove()">Remove</button></div>'}
function addAffRow(){document.getElementById("affRows").insertAdjacentHTML("beforeend",affRow())}
async function saveAff(slug){const offers=[...document.querySelectorAll(".affiliate-row")].map(r=>({retailer:r.querySelector(".ar-retailer").value,url:r.querySelector(".ar-url").value,label:r.querySelector(".ar-label").value})).filter(x=>x.retailer&&x.url);await api("/admin/api/shoes/"+encodeURIComponent(slug)+"/affiliates",{method:"PUT",body:JSON.stringify({affiliates:offers})});await load();render("affiliates")}
function posts(){shell("Blog Posts",'<div class="panel"><form id="pForm" class="form"><label>Title<input id="pTitle" required></label><div class="two"><label>Slug<input id="pSlug" placeholder="auto-generated"></label><label>Category<input id="pCategory" value="Sneakers"></label></div><label>Excerpt<input id="pExcerpt"></label><label>Content (Markdown)<textarea id="pContent" style="min-height:320px" placeholder="# Your article\n\nWrite your article here..."></textarea></label><div class="two"><label>SEO title<input id="pSeoTitle"></label><label>SEO description<input id="pSeoDescription"></label></div><button class="btn">Save draft</button><div id="pNotice"></div></form></div><div class="list">'+state.posts.map(p=>'<div class="row"><div><h3>'+esc(p.title)+'</h3><small>'+esc(p.file)+'</small></div></div>').join("")+'</div>');document.getElementById("pForm").onsubmit=async e=>{e.preventDefault();try{await api("/admin/api/posts",{method:"POST",body:JSON.stringify({title:pTitle.value,slug:pSlug.value,category:pCategory.value,excerpt:pExcerpt.value,content:pContent.value,seoTitle:pSeoTitle.value,seoDescription:pSeoDescription.value})});await load();render("posts");document.getElementById("pNotice").innerHTML='<div class="notice success">Draft created.</div>'}catch(err){pNotice.innerHTML='<div class="notice error">'+esc(err.message)+'</div>'}}}
navs.forEach(n=>n.onclick=()=>render(n.dataset.view));load();